ALTER TABLE CustomMatches ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE Whiteboards ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE MatchScouting ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE ScoutingQuestionSections ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE ScoutingQuestionGroups ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE ScoutingQuestions ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE ScoutingAnswers ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE Checklists ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE ChecklistQuestions ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE Alliances ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE Strategy ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE TeamComments ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;