ALTER TABLE CustomMatches ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE Whiteboards ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE MatchScouting ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ScoutingQuestionSections ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ScoutingQuestionGroups ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ScoutingQuestions ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ScoutingAnswers ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE Checklists ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ChecklistQuestions ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE Alliances ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE Strategy ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE TeamComments ADD COLUMN archive BOOLEAN NOT NULL DEFAULT 0;