// This file is automatically generated by the permissions manager, please do not edit

export type Permission =
    | 'editRoles'
    | 'viewData'
    | 'editDatabase'
    | 'editPermissions'
    | 'editUsers'
    | 'viewLogs'
    | 'verify'
    | 'editScoutingQuestions'
    | 'settings'
    | 'submitScoutingAnswers'
    | 'admin'
    | 'mentor';
